apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-system
  template:
    metadata:
      labels:
        app: library-system
    spec:
      containers:
        - name: library-system
          image: thilinamanawadu/library-system:latest
          ports:
            - containerPort: 8080
